alias g="cd /home/marc/Git/grand-schemer"
alias pb="cd /home/marc/Git/grand-schemer/web/pb"
alias tmux="TERM=xterm-256color tmux"
alias educ="cd /home/marc/Git/grand-schemer/web/education"
alias psych="cd /home/marc/Git/grand-schemer/teaching/psychnecon"
