alias g="cd /home/marc/Git/grand-schemer"
alias pb="cd /home/marc/Git/grand-schemer/web/pb"
alias tmux="TERM=xterm-256color tmux"
alias educ="cd /home/marc/Git/grand-schemer/web/education"
alias psych="cd /home/marc/Git/grand-schemer/teaching/psychnecon"
alias bus="cd /home/marc/Git/grand-schemer/teaching/business-economics"
alias infoecon="cd /home/marc/Git/grand-schemer/teaching/information-economics"
alias study="cd /home/marc/Git/study-time"
alias mturk="cd /home/marc/Git/grand-schemer/mturk-experiment"
alias diss="cd /home/marc/Git/grand-schemer/dissertation"
alias ra="cd /home/marc/Git/matthew-ra"
alias auth="./Desktop/mkaufmann-openauth/mkaufmann-openauth.sh"
alias rc-login="ssh mkaufmann@login.rc.fas.harvard.edu"
alias mm="mysql -u mturk -p mturk_pilot"
alias mb="mysql -u beliefs -p beliefs2016"
