source-file ~/.tmux.conf
new-session -s educ-proposal -n proposal -d
send-keys -t educ-proposal 'cd ~/Git/grand-schemer/web/education' C-m
send-keys -t educ-proposal 'vi education-proposal.md' C-m
split-window -v -t educ-proposal
select-layout -t educ-proposal main-horizontal
send-keys -t educ-proposal:1.2 'cd ~/Git/grand-schemer/web/education' C-m
select-pane -t educ-proposal:1.1
