source-file ~/.tmux.conf
new-session -s pb-draft -n draft -d
send-keys -t pb-draft 'cd ~/Git/grand-schemer/web/pb' C-m
send-keys -t pb-draft 'vi gd-intro.md' C-m
split-window -v -t pb-draft
select-layout -t pb-draft main-horizontal
send-keys -t pb-draft:1.2 'cd ~/Git/grand-schemer/web/pb' C-m
select-pane -t pb-draft:1.1
