# Set prefix to Ctrl-a
unbind C-b
set -g prefix C-a

# Delay keypresses for shorter timespans
set -s escape-time 1

# Start counting panes and windows at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Bind 'r' to reload this configuration file on the fly
# \; allows one to separate multiple commands on one line.
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Pass through Ctrl-a when Ctrl-a is pressed twice.
bind C-a send-prefix

# Split windows horizontally with -, vertically with |
bind - split-window -v
bind | split-window -h
